### ISSUE TITLE
Continuous integration as a kit requirement

### ISSUE THREAD

**Issue by ianmkenney** [MDAnalysis/MDAKits#96]
In the Scipy paper we have CI as a requirement for kit registration. Since we don't have checks for this (missing in the metadata specification), we will need to check manually per submission. Additionally, the CI can be run in a variety of ways/places that may not be obvious. Should we add an optional string to the metadata for a CI URL?

**Comment by IAlibay** [comment]
:/ I'll have to reread the paper but that was not meant to be a registration requirement!

**Comment by IAlibay** [comment]
I see now that it says "tests and continuous integration" - I thought I had pushed back on that wording to only be tests being required.. pinging @orbeckst here

**Comment by orbeckst** [comment]
The paper states 

> Tests and continuous integration (required)

and then we specifically require tests

> *We require* at least a single regression test for major functionality to qualify for the registry

(my emphasis) but only encourage CI

> To ensure that tests are run regularly, the *recommended best practice* is to implement a continuous integration pipeline that performs the tests every time new code is introduced. *We encourage* the use of free pipelines such as GitHub Actions [37] to implement continuous integration.

That may not have been the clearest way to express it. 

Last time I looked up the requirements, I used the requirements bullet points from the paper and therefore assumed that we ultimately require both tests and CI, and that's why I wrote https://mdakits.mdanalysis.org/about.html#what-is-an-mdakit in the way it is at the moment: reflecting what's written in the paper. 

I suggest we rewrite what's on the MDAKits page as

> 6. At least minimal regression tests are present; continuous integration is encouraged.

In this way we are still pretty much consistent with the paper.

**Comment by IAlibay** [comment]
Thanks for looking into this @orbeckst - I think I see how this confusion ended up sneaking into the paper now :/ I probably should have paid more attention.

Thanks for the fixed wording!
