### ISSUE TITLE
require source installation in metadata

### ISSUE THREAD

**Issue by ianmkenney** [MDAnalysis/MDAKits#98]
Since the FAIR4RS requires that source is accessible, we should make the `src_install` field required. From there I think it's fair to keep `install` as an optional field.

**Comment by IAlibay** [comment]
So there's a difference between `src_install` and `project_home`, the latter is the one that we want to enforce for FAIR4RS.

The reason for this distinction, and not enforcing a `src_install`, is because early on in the MDAKits process we agreed that we wanted to be able to handle mdakits being submitted that weren't fully packaged - i.e. that sometimes someone might come along with a script in a github repo and that would be ok.

That being said, we should revisit this discussion.

**Comment by orbeckst** [comment]
Btw, what happens in the registry if either `install` or `src_install` (or both) are missing, @IAlibay ?

**Comment by IAlibay** [comment]
> Btw, what happens in the registry if either `install` or `src_install` (or both) are missing, @IAlibay ?

I believe the badges just go "grey" - i.e. "could not run this".

**Comment by IAlibay** [comment]
> We do require installation instructions so they must be able to provide them in a form that we can execute.

That is a very good point. I'm also convinced, however I think the "looser" requirements came from other folk's views (I think @jbarnoud might have been a proponent of this?). Either way, we should at least rope in @lilyminium and @fiona-naughton on this discussion.

**Comment by jbarnoud** [comment]
I haven't followed mdakit for a long while so I am lacking context.  Bouncing on an earlier comment of Irfan, the two main ideas I had about the project were:
* the amount of mandatory maintenance should be minimal (it can keep workibgbif nobody has time to regularly spend on it)
* the barrier for entry should be as low as possible to encourage new comers imbrue mdakit ecosystem. Often, we have PhD candidates or postdoc that have tools but won't share their code because they do not know how. Rather than scare them by telling them their project is not good enough, we should encourage them to share first and then give them incentives to improve. For instance: create a package and we can add you to our ci and add to to the better list of kits.

**Comment by orbeckst** [comment]
I agree that we want to encourage people to share. Minimal testing is, however, one of those requirements where we drew a line, as spelled out in our requirements for becoming a registered kit https://mdakits.mdanalysis.org/about.html#what-is-an-mdakit . I don't think we want to remove this requirement, do we?

Personally, I do believe in the "untested code is broken code" adage" and I see part of our mission to educate on minimal best practices. From my experience, people are more motivated to go the extra mile when they want to achieve something (like getting a kit registered) as opposed to "coming back later to add tests when I have time".

If we want a two-tiered registry where we have tested kits with green badges and a "second tier" of kits that are effectively just links without badges or red badges then we need to discuss it.

> and we can add you to our ci 

That's exactly what we're doing, but in order to do it we need to know

* How to install your package?
* How to run your tests?

**Comment by orbeckst** [comment]
@fiona-naughton and @lilyminium please have a look at this issue and the related #95 on making three important parameters in the registration yaml file *required*. Your comments would be very much appreciated!

The parameters are

- `source_install`: commmands to install the software from source

   https://github.com/MDAnalysis/MDAKits/blob/9f729e8e1ab2dd4dfc6c6f755a8afb5c9205d12f/mdakits/template/metadata.yaml#L67-L70

- `run_tests` and `test_dependencies`: commands to run tests and to install any deps for the tests

  https://github.com/MDAnalysis/MDAKits/blob/9f729e8e1ab2dd4dfc6c6f755a8afb5c9205d12f/mdakits/template/metadata.yaml#L81-L101

[Requirements for a (registered) MDAKit](https://mdakits.mdanalysis.org/about.html#what-is-an-mdakit) are in the paper and summarized on our web site.

One reason why they are currently optional was related to keeping the barrier to entry low, as expressed in https://github.com/MDAnalysis/MDAKits/issues/98#issuecomment-1808773002 and https://github.com/MDAnalysis/MDAKits/issues/98#issuecomment-1809960174 .

**Comment by fiona-naughton** [comment]
Restarting this discussion having been reminded when writing the reviewer's guide - my apologies for not having commented at the time. 

I would tend to agree with Oliver; I understand stuff like writing tests can be a daunting barrier, but I would consider it one of the key aims of MDAKits to be making this barrier as low as possible so we are building up scientists who know how to write better code (with the cookie cutter and instructions, hopefully some additional resources I'm planning to put together, reviewers there to provide advice, the incentive of registering a kit, etc), rather than removing it entirely by making it optional - which just delays the issue (similar to what Oliver said, if that first step isn't now, I'm not sure I see them coming back to take it later). It's also in line with how we've been selling it to users.

(It doesn't need to be super comprehensive tests - the biggest barrier imo is understanding the general idea and format, so as long as they've encountered that, hopefully building out more coverage is a lot less scary and more likely to happen) 

(Also, it'll be easier to relax a compulsory rule in the future if we do decide it's too off putting, then have to instate it and need to sort through everything that's already been registered)

**Comment by orbeckst** [comment]
I'd like to revive this issue together with #95 and come to a decision. Can we discuss at the next MDAKits meeting?

**Comment by orbeckst** [comment]
I put it on the agenda for the 2024-07-17 meeting.

**Comment by orbeckst** [comment]
At the EOSS4 MDAKits meeting on Jul 17, the MDAKits team decided that we want to make minimal tests and installation from source MANDATORY and thus enforce it during reviews.

In a subsequent round of consultations with the CoreDevs, there were a number of positive comments and no objections.

Therefore, **minimal tests and installation from source instructions are MANDATORY** and enforceable during review.

**Comment by orbeckst** [comment]
Completed with PR #159
